name: Run Tests on Push
on: 
  push:
    branches:
      - 'main'
      - 'requirement_fix'

jobs: 
  Tests-On-Push:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute test scripts
        run: |
          printf '=======================================Testing kafka utils=======================================\n' > tests/logs/test_report.log
          python3 -m pytest tests/data_collection/test_kafka_utils.py >> tests/logs/test_report.log
          printf '\n\n\n\n=======================================Testing movie utils=======================================\n' >> tests/logs/test_report.log
          python3 -m pytest tests/data_collection/test_movie_utils.py >> tests/logs/test_report.log
          printf '\n\n\n\n=======================================Testing rest_api utils=======================================\n' >> tests/logs/test_report.log
          python3 -m pytest tests/data_collection/test_rest_api_utils.py >> tests/logs/test_report.log
          printf '\n\n\n\n=======================================Coverage=======================================\n' >> tests/logs/test_report.log
          coverage run --omit=/usr/* -m pytest && coverage report >> tests/logs/test_report.log
          python3 rsmodel.py True True > tests/logs/offline_train_report.log
          python3 data_collection/collect_processed.py data 500000
          git pull
          

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add tests
          git diff-index --quiet HEAD || (git commit -a -m "Automated tests on push and logs update." --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          