name: Periodic Training
on:
  schedule:
  workflow_dispatch:
  
jobs: 
  Periodic_training:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute test scripts
        run: |
          printf '=======================================Auto training & deployment=======================================\n'
          python3 auto_deployment.py > tests/logs/auto_deployment.log
